### PR TITLE
procrustes optimization

### PR DESCRIPTION
**Pull request by bbbxyz**
optimizations for calculating the traces of matrices

### CODE REVIEW

**Comment by vfonov** [comment]
Do we really need to optimize it?

**Comment by bbbxyz** [comment]
` matrix_multiply( npoints, ndim, npoints, ... , ... , product )` attempts to allocate an npoints*npoints 2D array which can causes issues if npoints is large

**Comment by vfonov** [comment]
In my experience npoints is usually around 10 , do you have a special use case?

**Comment by bbbxyz** [comment]
Using tag2xfm followed by xfmtotag to estimate a linear transformation from an arbitrary one. If the number of tag points extracted is large then tagtoxfm will fail.

**Comment by vfonov** [comment]
ok, I suppose we should make sure that xfm2tag will not fail when somebody tries to run rigid body registration with a million tag points.

**Comment by vfonov** [comment]
Maybe you could also make a test for tagtoxfm to test this use case? 
https://github.com/BIC-MNI/bicpl/tree/develop/Testing

**Comment by bbbxyz** [comment]
I will get on that

**Comment by vfonov** [comment]
that would be good, thank you!

**Pull request merged**
