### PR TITLE
Prog_utils: add time.h include

### PR DESCRIPTION
**Pull request by RaghavSood**
The build for bicpl in [nixpkgs](https://github.com/NixOS/nixpkgs) has been broken for some time.

The `apple-develop` branch fixes two of the issues - however, a missing `time.h` still prevents a build without additional patches.

I would like to get this into upstream to avoid having to maintain a separate patch just for one line.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Can you please provide the build failure this fixes?

**Comment by RaghavSood** [comment]
Attaching the build log of the failure.

It's a common failure we're seeing across multiple packages as we update the C tooling, in this case standardizing clang 16 as default: https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#potentially-breaking-changes

[bicpl.log](https://github.com/BIC-MNI/bicpl/files/15301542/bicpl.log)

**Comment by gdevenyi** [comment]
Thanks, very clear, we're missing the include and it eventually gets linked in elsewhere, but clang-16 won't let us do that anymore.

**Comment by RaghavSood** [comment]
Thank you! I'll make an update to nixpkgs to remove the patch and pull [7e1e791](https://github.com/BIC-MNI/bicpl/commit/7e1e791483cf135fe29b8eecd7a360aa892823ae).

**Pull request merged**
